---
- hosts: localhost
  connection: local
  sudo: no

  roles:
    - { role: virt-import, 
        ova_path: ~/Downloads/Sandbox_HDP_2.2.4.2_VirtualBox.ova,
        ova_dir: ~/Downloads/Sandbox_HDP_2.2.4.2_VirtualBox
      }
    - { role: virt-mount,
        domain_name: "Hortonworks Sandbox with HDP 2.2.4.2",
        mount_dir: ~/Projects
      }
    - hdp-sandbox-virt-guest
